/* Copyright (c) 2021-2026 Richard Rodger, MIT License */

// Generated by ../embed-translate.js. Edit tabnas.plugin.json or alchemy/*,
// then run npm run embed.

type TranslationPart = Readonly<{
  entry: string
  source?: string
}>

type TranslationParts = Readonly<{
  manifest: string
  lift?: TranslationPart
  embed?: TranslationPart
  render?: TranslationPart
}>

const TRANSLATION: TranslationParts = Object.freeze({
  manifest: `{
  "$schema": "https://tabnas.dev/schema/plugin.schema.json",
  "name": "@tabnas/toml",
  "go": "github.com/tabnas/toml/go",
  "rust": "tabnas-toml",
  "description": "TOML parsing for the tabnas engine.",
  "base": "@tabnas/jsonic",
  "engine": "@tabnas/parser",
  "grammar": "toml-grammar.jsonic",
  "extensions": [
    ".toml"
  ],
  "mediaTypes": [
    "application/toml"
  ],
  "languageId": "toml",
  "pluginKind": "grammar",
  "grammarKind": "closure",
  "lexStream": "clean",
  "syncGroups": [
    "end",
    "comma",
    "close"
  ],
  "specDir": "test/spec",
  "clib": {
    "dir": "go/clib",
    "library": "libtabnastoml",
    "abi": "v1",
    "errorCodes": [
      "usage",
      "grammar",
      "handle",
      "internal"
    ]
  },
  "errorCodes": [
    "toml_key_conflict",
    "invalid_datetime"
  ],
  "docs": "https://tabnas.dev/docs/packages",
  "repository": "https://github.com/tabnas/toml",
  "versionSource": "ts/package.json",
  "translate": {
    "reads": "tree",
    "writes": "tree",
    "root": "object",
    "render": "alchemy/render.alc",
    "loss": [
      "Comments are not kept.",
      "Every key is written as a quoted key, and every table under a key as an inline table on that key's line.",
      "Every string is written as a basic string on one line, its line breaks escaped; a literal or multi-line string is not kept as one.",
      "A date or time is written as a string, since the reader builds one as text.",
      "A number is written as JSON writes its value, not as the document spelled it: a hexadecimal, octal or binary integer, an underscore and an exponent are not kept, and a whole float such as 1.0 is written as an integer.",
      "A null is not written: a member whose value is null is omitted, and a null element of an array is skipped.",
      "An integer TOML's 64-bit integers cannot hold, below -9223372036854775808 or above 9223372036854775807, is written as a float, its digits followed by .0, and reads back as the nearest double; a number that is not finite is written inf, -inf or nan, whatever its lexeme."
    ],
    "whole": "A table may be added to after the tables that follow it, by a later header, dotted key or array of tables, so a document's tree is complete only at its end: it is read whole before anything is written."
  }
}
`,
  render: Object.freeze({ entry: "toml-render", source: `; TOML's render: a tree's events written as one TOML 1.0 document. This
; is a library of definitions, each named \`toml-...\`, which a host links
; with its own program (alchemy's \`compile_sources\`); its entry point is
; \`toml-render\`, and nothing else here is the host's to call.
;
; The profile is always-quoted, as the YAML and CSV renders' are: every
; key is a quoted key and every string a basic string, both through
; \`quoted\` (JSON's escapes, which TOML's basic strings read, with the
; controls TOML forbids in one written as \`\\uXXXX\`), since alchemy cannot
; tell a bare key from one that has to be quoted. The root is the one
; table, each member on its own line as \`"key" = value\`; a table under a
; key is an inline table on that line, \`{ "k" = v, "k2" = v2 }\`, and \`{}\`
; when empty, since TOML 1.0 keeps an inline table to one line with no
; trailing comma; an array is \`[ v, v ]\`, and \`[]\` when empty, and may
; hold inline tables and arrays. A number is its lexeme, or as the JSON
; renderer writes it when it has none, which is how every number reaches
; a render from a parsed TOML document (so \`1.0\` is written as \`1\`); an
; integer TOML's 64-bit integers cannot hold is written as a float, \`.0\`
; after its digits, which TOML reads as the double nearest it, as a JSON
; reader does; and a number that is not finite is \`inf\`, \`-inf\` or \`nan\`,
; whatever its lexeme. A boolean is \`true\` or \`false\`.
;
; TOML has no null, so a null is not written, as \`toml-options\` says: a
; member whose value is null is omitted, key included, and a null element
; of an array is skipped, with no separator left behind. So \`[1, null, 2]\`
; is written \`[ 1, 2 ]\` and \`[null]\` is \`[]\`, an inline table whose
; members are all null is \`{}\`, and a document whose root members are all
; null is written as no text at all. That is why a key is not written
; when it arrives: it is held, and written with the first event of its
; value (a scalar, the start of a table, the start of an array), or
; dropped unwritten with a null.
;
; The root must be a table, since TOML's document is one: any other root
; fails with TARGET_VALUE_UNREPRESENTABLE, saying what it is. A host that
; composes the render puts any other root under a key of a table first,
; as the manifest's \`root\` (\`object\`) asks, so only a caller that runs
; the render directly meets that refusal.
;
; The events are a tree's: a table holds each key once. A walked value
; is one by construction; a host that streams a parse must refuse a
; member the parse repeats, since the render writes what it is given and
; TOML forbids a key defined twice.
;
; The state is the stack of open containers, one marker each, and the
; key it holds, at most one, so it grows with a document's nesting and
; never with its width: \`:root\` for the root table waiting for a key,
; \`[:key name]\` above its table's marker for a key held until its value
; begins, \`:member\` for a root member whose value is being written,
; \`:table-open\` for an inline table with nothing written yet, \`:table\` for
; one waiting for its next key, \`:table-member\` for its member whose value
; is being written, \`:array-open\` for an array with nothing written yet
; and \`:array\` for one waiting for its next item. The separators are
; decided by the marker, so no container counts its members, and a null
; that is not written leaves its container's marker as it was. Once the
; root table ends the state is \`[:root-done]\`, and nothing may follow it.
; Events no tree has fail with PROTOCOL_ORDER_ERROR, saying so.

; The render's policies, each read where it applies. \`:null\` is how a
; null is written where a value is due: \`:omit\`, the one policy, writes
; nothing, so a member whose value is null is not written, key included,
; and a null element of an array is skipped.
def toml-options
  record
    entry :null :omit

; The top marker, or \`:none\` before the root value.
def toml-top [s]
  match (count s)
    case 0 :none
    case _ (top s)

; The top container under another marker.
def toml-mark [marker s]
  push marker (pop s)

; A key, held above its table's marker until the first event of its value
; writes it or a null drops it. At most one is held, since the event after
; a key is its value's.
def toml-key [name s]
  match (toml-top s)
    case :root (transition (push [:key name] s) [])
    case :table-open (transition (push [:key name] s) [])
    case :table (transition (push [:key name] s) [])
    case _ (fail :protocol-order "the events hold a key where a value is due, which a tree's never do")

; What leads a key in the table at the top of s: nothing at the start of
; a root member's line, a space after an inline table's opening brace and
; \`, \` after its last member.
def toml-key-lead [s]
  match (toml-top s)
    case :root ""
    case :table-open " "
    case :table ", "

; What comes before a value whose parent is the top of s: the key held for
; it, led as its table needs and followed by \` = \`; a space before an
; array's first item and \`, \` before a later one.
def toml-lead [s]
  match (toml-top s)
    case [:key name] (string-join "" [(toml-key-lead (pop s)) (quoted name) " = "])
    case :array-open " "
    case :array ", "
    case _ (fail :protocol-order "the events hold a value where a key is due, which a tree's never do")

; The state once a value begins under the top of s: a held key is
; written, so its table's marker says that a member's value is being
; written, and a held array is opened by its first item.
def toml-entered [s]
  match (toml-top s)
    case [:key _]
      match (toml-top (pop s))
        case :root (toml-mark :member (pop s))
        case _ (toml-mark :table-member (pop s))
    case :array-open (toml-mark :array s)
    case _ s

; A value completed under the top of s: the root table waits for its
; next key, an inline table for its next key, an array for its next item.
def toml-done [s]
  match (toml-top s)
    case :member (toml-mark :root s)
    case :table-member (toml-mark :table s)
    case _ s

; What follows a value completed under the top of s: a root member's
; line ends.
def toml-close [s]
  match (toml-top s)
    case :member "\\n"
    case _ ""

; A number: a finite one by its text, as \`toml-finite\` writes it, and one
; that is not finite as TOML spells it, \`inf\`, \`-inf\` or \`nan\`, whatever
; its lexeme (JSON's \`1E400\` is \`inf\`).
def toml-number [n]
  match (number-class n)
    case :finite (toml-finite (scalar-text csv-options n))
    case :infinity "inf"
    case :negative-infinity "-inf"
    case :nan "nan"

; A finite number's text, its lexeme or the JSON renderer's text of its
; value: as it is, unless it is an integer TOML's 64-bit integers cannot
; hold, which is written as a float, \`.0\` after its digits, so that TOML
; reads the double nearest the integer, as a JSON reader reads it.
def toml-finite [text]
  match (toml-integer-fits text)
    case true text
    case false (string-join "" [text ".0"])

; The characters of a non-negative integer's text, and of any integer's.
def toml-digits [[48 57]]

def toml-integer-chars [[45 45] [48 57]]

; The two doubles either side of 2^63 x 10^23, the upper one and the
; lower one negated. 2^63 x 10^23 is 5^23 x 2^86, and 5^23 is odd and one
; bit longer than a double's significand, so it is exactly their midpoint.
def toml-above-midpoint 9.223372036854777e+41

def toml-below-midpoint-negated -9.223372036854775e+41

; Whether a number's text is a float's, or an integer's that TOML's
; integers hold, from -9223372036854775808 to 9223372036854775807. An
; integer's text is digits, after a minus sign when it is negative; a
; float's has a point or an exponent besides. The count of digits decides,
; but at nineteen, where the range ends, a double cannot: \`compare\` sees
; every integer from 2^63-512 to 2^63+1024 as the one double 2^63. So the
; text is scaled by 10^23 and read as a number, whose rounding to the
; doubles either side of the midpoint 2^63 x 10^23 decides exactly: a
; non-negative n followed by \`5e22\`, n x 10^23 + 5 x 10^22, rounds to the
; upper one or above exactly when n is 2^63 or more, and a negative -n
; followed by \`e23\`, -n x 10^23, rounds below the lower one negated
; exactly when n is more than 2^63, since the midpoint itself, 2^63
; scaled, rounds to the one whose significand is even, the lower.
def toml-integer-fits [text]
  match (chars-within toml-digits text)
    case true
      match (compare (length text) 19)
        case :less true
        case :greater false
        case :equal
          match (compare (number (string-join "" [text "5e22"])) toml-above-midpoint)
            case :less true
            case _ false
    case false
      match (chars-within toml-integer-chars text)
        case false true
        case true
          match (compare (length text) 20)
            case :less true
            case :greater false
            case :equal
              match (compare (number (string-join "" [text "e23"])) toml-below-midpoint-negated)
                case :less false
                case _ true

; A null where a value is due at the top of s, as \`toml-options\` says.
def toml-null [s]
  match (get :null toml-options)
    case :omit (toml-omit s)

; A null not written: a member's drops the key held for it, unwritten,
; and an array's leaves the array as it was, so no separator is left
; behind.
def toml-omit [s]
  match (toml-top s)
    case [:key _] (transition (pop s) [])
    case :array-open (transition s [])
    case :array (transition s [])
    case _ (fail :protocol-order "the events hold a value where a key is due, which a tree's never do")

; A scalar other than null: a string as a basic string, a number by its
; lexeme or its value, a boolean by its name.
def toml-scalar [value]
  match (kind value)
    case :boolean
      match value
        case true "true"
        case false "false"
    case :number (toml-number value)
    case _ (quoted value)

; A scalar due at the top of s, written with what leads it and what
; follows it, or a null, written as \`toml-options\` says.
def toml-value [value s]
  match (kind value)
    case :null (toml-null s)
    case _
      let [s2 (toml-entered s)]
        transition (toml-done s2) [(toml-lead s) (toml-scalar value) (toml-close s2)]

; A root that is not a table: TOML's document is one.
def toml-root-scalar [value]
  match (kind value)
    case :null (fail :unrepresentable "TOML's root is a table: the document's root is null, which TOML cannot carry")
    case :boolean (fail :unrepresentable "TOML's root is a table: the document's root is a boolean, which TOML cannot carry")
    case :number (fail :unrepresentable "TOML's root is a table: the document's root is a number, which TOML cannot carry")
    case _ (fail :unrepresentable "TOML's root is a table: the document's root is a string, which TOML cannot carry")

def toml-step [s event]
  match (toml-top s)
    case :root-done (fail :protocol-order "the events hold more after the root table, which a tree's never do")
    case _ (toml-event s event)

def toml-event [s event]
  match event
    case object-start
      match (toml-top s)
        case :none (transition [:root] [])
        case _ (transition (push :table-open (toml-entered s)) [(toml-lead s) "{"])
    case array-start
      match (toml-top s)
        case :none (fail :unrepresentable "TOML's root is a table: the document's root is an array, which TOML cannot carry")
        case _ (transition (push :array-open (toml-entered s)) [(toml-lead s) "["])
    case (key name) (toml-key name s)
    case (scalar value)
      match (toml-top s)
        case :none (toml-root-scalar value)
        case _ (toml-value value s)
    case object-end
      match (toml-top s)
        case :root (transition [:root-done] [])
        case :table-open
          transition (toml-done (pop s)) ["}" (toml-close (pop s))]
        case :table
          transition (toml-done (pop s)) [" }" (toml-close (pop s))]
        case [:key _]
          fail :protocol-order "the events end a table after a key and before its value, which a tree's never do"
        case _
          fail :protocol-order "the events end a table that is not open, which a tree's never do"
    case array-end
      match (toml-top s)
        case :array-open
          transition (toml-done (pop s)) ["]" (toml-close (pop s))]
        case :array
          transition (toml-done (pop s)) [" ]" (toml-close (pop s))]
        case _
          fail :protocol-order "the events end an array that is not open, which a tree's never do"

def toml-finish [s]
  match (toml-top s)
    case :root-done []
    case :none (fail :protocol-order "the events hold no value, where a tree's hold one")
    case _ (fail :protocol-order "the events ended inside a container")

; The render: the tree's events in, the document's text out.
def toml-render [input]
  join ""
    scan-emit [] toml-step toml-finish (events input)
` })
})

function translate (): TranslationParts | undefined {
  return TRANSLATION
}

export {
  translate,
}

export type {
  TranslationPart,
  TranslationParts,
}
